export interface Artwork {
  id: string
  slug: string
  title: string
  year: string
  medium: string
  dimensions: string
  description: string
  image: string
  thumbnail?: string
  // Natural pixel dimensions of the image file
  imgWidth: number
  imgHeight: number
}

export const artworks: Artwork[] = [
  {
    id: "1",
    slug: "blossom-bleach-2019",
    title: "Blossom Bleach",
    year: "2019",
    medium: "Oil on hardboard",
    dimensions: "30 × 40 cm",
    description: "Floral beauty stripped of color and vitality. The painting explores the paradox of bleached blossoms—delicate forms drained of their vibrancy, finding unexpected grace in absence and the erosion of chromatic intensity. 30 × 40 cm",
    image: "/paintings/blossom-bleach-2019.jpg",
    thumbnail: "/paintings/blossom-bleach-2019.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "2",
    slug: "in-der-tiefe-2024",
    title: "In der Tiefe",
    year: "2024",
    medium: "Oil on canvas",
    dimensions: "95 × 125 cm",
    description: "A journey into depth, both visual and emotional. The painting unfolds through layers of color and form, drawing the viewer into an intimate space of introspection and discovery. 95 × 125 cm",
    image: "/paintings/in-der-tiefe-2024.jpg",
    thumbnail: "/paintings/in-der-tiefe-2024.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "3",
    slug: "chartreuse-2020",
    title: "Chartreuse",
    year: "2020",
    medium: "Oil on canvas",
    dimensions: "95 × 115 cm",
    description: "A vibrant exploration of greenish-yellow tones and their emotional resonance. The painting captures the intensity and vitality of this complex color family, exploring how hue and saturation interact to create atmospheric depth. 95 × 115 cm",
    image: "/paintings/chartreuse-2020.jpg",
    thumbnail: "/paintings/chartreuse-2020.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "4",
    slug: "herbstglanz-2022",
    title: "Herbstglanz",
    year: "2022",
    medium: "Oil on canvas",
    dimensions: "115 × 130 cm",
    description: "A celebration of autumn's luminous beauty. Warm tones blend and dissolve across the canvas, capturing the transient glow of seasonal transition and the richness of fading light. 115 × 130 cm",
    image: "/paintings/herbstglanz-2022.jpg",
    thumbnail: "/paintings/herbstglanz-2022.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "5",
    slug: "dans-loeil-du-silence-2022",
    title: "Dans l'oeil du Silence",
    year: "2022",
    medium: "Oil on canvas",
    dimensions: "115 × 150 cm",
    description: "In the eye of silence, a contemplation of stillness and presence. The work captures a moment suspended between sound and quiet, where color becomes language and form dissolves into feeling. 115 × 150 cm",
    image: "/paintings/dans-loeil-du-silence-2022.jpg",
    thumbnail: "/paintings/dans-loeil-du-silence-2022.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "6",
    slug: "il-risveglio-delle-forme-2021",
    title: "Il Risveglio Delle Forme",
    year: "2021",
    medium: "Oil on canvas",
    dimensions: "89 × 114 cm",
    description: "The awakening of forms—a meditation on emergence and becoming. Shapes and colors rise from the canvas surface, suggesting the quiet moment when form first stirs into existence. 89 × 114 cm",
    image: "/paintings/il-risveglio-delle-forme-2021.jpg",
    thumbnail: "/paintings/il-risveglio-delle-forme-2021.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "7",
    slug: "primavera-delle-forme-2021",
    title: "Primavera Delle Forme",
    year: "2021",
    medium: "Oil on canvas",
    dimensions: "89 × 114 cm",
    description: "Spring of forms—a celebration of renewal and emergence. Color and light interweave to evoke the first stirrings of new life, where shapes blossom from the canvas in quiet anticipation. 89 × 114 cm",
    image: "/paintings/primavera-delle-forme-2021.jpg",
    thumbnail: "/paintings/primavera-delle-forme-2021.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "8",
    slug: "autunno-delle-forme-2021",
    title: "Autunno Delle Forme",
    year: "2021",
    medium: "Oil on canvas",
    dimensions: "89 × 114 cm",
    description: "Autumn of forms—a reflection on transformation and release. Warm earth tones merge and shift, capturing the quiet dignity of decline and the beauty found in letting go. 89 × 114 cm",
    image: "/paintings/autunno-delle-forme-2021.jpg",
    thumbnail: "/paintings/autunno-delle-forme-2021.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "9",
    slug: "once-upon-a-time-below-2021",
    title: "Once Upon A Time Below",
    year: "2021",
    medium: "Oil on canvas",
    dimensions: "88 × 114 cm",
    description: "A narrative hidden beneath the surface. Layers of time and memory intertwine, telling stories of what lies below consciousness—a poetic journey into the depths of imagination and the past. 88 × 114 cm",
    image: "/paintings/once-upon-a-time-below-2021.jpg",
    thumbnail: "/paintings/once-upon-a-time-below-2021.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "10",
    slug: "crumble-peat-2021",
    title: "Crumble Peat",
    year: "2021",
    medium: "Oil on canvas",
    dimensions: "80 × 105 cm",
    description: "Fragmented earth and time crumble into memory. The painting explores the decay of natural forms and the way the earth preserves its stories through layered sediment and weathered texture. 80 × 105 cm",
    image: "/paintings/crumble-peat-2021.jpg",
    thumbnail: "/paintings/crumble-peat-2021.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "11",
    slug: "twinkling-twilight-2021",
    title: "Twinkling Twilight",
    year: "2021",
    medium: "Oil on canvas",
    dimensions: "63 × 89 cm",
    description: "The luminous moments between day and night capture delicate light dancing across form. Soft glimmers emerge from darker passages, suggesting the fleeting beauty of transition and the magic found in the in-between. 63 × 89 cm",
    image: "/paintings/twinkling-twilight-2021.jpg",
    thumbnail: "/paintings/twinkling-twilight-2021.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "12",
    slug: "ciel-de-mur-de-pierre-2021",
    title: "Ciel de Mur de Pierre",
    year: "2021",
    medium: "Oil on canvas",
    dimensions: "105 × 110 cm",
    description: "Sky of stone wall—a meditation on the boundary between nature and structure. Stone surfaces converge with atmospheric depth, exploring the dialogue between solid form and infinite space. 105 × 110 cm",
    image: "/paintings/ciel-de-mur-de-pierre-2021.jpg",
    thumbnail: "/paintings/ciel-de-mur-de-pierre-2021.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "13",
    slug: "terre-brillante-fragmente-2020",
    title: "Terre Brillante Fragmenté",
    year: "2020",
    medium: "Oil on canvas",
    dimensions: "70 × 90 cm",
    description: "Fragmented brilliant earth—a study of light breaking through textured surfaces. The painting explores how luminosity emerges from the interplay of broken forms and shifting planes of color. 70 × 90 cm",
    image: "/paintings/terre-brillante-fragmente-2020.jpg",
    thumbnail: "/paintings/terre-brillante-fragmente-2020.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "14",
    slug: "zwischenraeume-2023",
    title: "Zwischenräume",
    year: "2023",
    medium: "Oil on canvas",
    dimensions: "95 × 110 cm",
    description: "An exploration of the spaces between—liminal zones where color and form dissolve into atmosphere, inviting contemplation of what lies beyond the visible. 95 × 110 cm",
    image: "/paintings/zwischenraeume-2023.jpg",
    thumbnail: "/paintings/zwischenraeume-2023.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "15",
    slug: "midsummer-mitigation-2020",
    title: "Midsummer Mitigation",
    year: "2020",
    medium: "Oil on canvas",
    dimensions: "92 × 66 cm",
    description: "A meditation on balance amid the intensity of summer's peak. Cooling tones and warm passages engage in quiet negotiation, seeking equilibrium between opposing forces and finding harmony in their tension. 92 × 66 cm",
    image: "/paintings/midsummer-mitigation-2020.jpg",
    thumbnail: "/paintings/midsummer-mitigation-2020.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "16",
    slug: "sheer-invention-2020",
    title: "Sheer Invention",
    year: "2020",
    medium: "Oil on canvas",
    dimensions: "70 × 90 cm",
    description: "Pure creative expression unfolds across the canvas. The painting celebrates the act of invention itself—where imagination takes physical form through color, gesture, and the spontaneous emergence of structure from intuition. 70 × 90 cm",
    image: "/paintings/sheer-invention-2020.jpg",
    thumbnail: "/paintings/sheer-invention-2020.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "17",
    slug: "pallid-paleosome-2020",
    title: "Pallid Paleosome",
    year: "2020",
    medium: "Oil on canvas",
    dimensions: "62 × 89 cm",
    description: "A study of ancient traces and weathered remnants. Pale, subtle tones evoke the fossil record of color and form, exploring how time leaves its delicate imprint across the surface of matter and memory. 62 × 89 cm",
    image: "/paintings/pallid-paleosome-2020.jpg",
    thumbnail: "/paintings/pallid-paleosome-2020.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "18",
    slug: "jauntre-pas-trop-chaud-2020",
    title: "Jaunâtre Pas Trop Chaud",
    year: "2020",
    medium: "Oil on canvas",
    dimensions: "75 × 95 cm",
    description: "A subtle play on yellow-toned warmth—never too intense, always measured. The painting explores restraint and temperance through nuanced color shifts, finding richness in understatement and quiet sophistication. 75 × 95 cm",
    image: "/paintings/jauntre-pas-trop-chaud-2020.jpg",
    thumbnail: "/paintings/jauntre-pas-trop-chaud-2020.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "19",
    slug: "supra-terra-2019",
    title: "Supra Terra",
    year: "2019",
    medium: "Oil on hardboard",
    dimensions: "36 × 24 cm",
    description: "Above the earth—a diptych exploring elevation and transcendence. This two-part work on hardbord investigates the relationship between terrestrial and ethereal realms, where solid matter meets the infinite. 36 × 24 cm, two-part",
    image: "/paintings/supra-terra-2019.jpg",
    thumbnail: "/paintings/supra-terra-2019.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "20",
    slug: "babel-2019",
    title: "Babel",
    year: "2019",
    medium: "Oil on hardboard",
    dimensions: "24 × 18 cm",
    description: "A compact meditation on confusion, communication, and the collapse of understanding. This intimate work on hardbord explores the tower of tangled voices and fragmented meanings, where connection dissolves into layers of competing forms. 24 × 18 cm",
    image: "/paintings/babel-2019.jpg",
    thumbnail: "/paintings/babel-2019.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "21",
    slug: "zauber-der-erinnerung-2024",
    title: "Zauber der Erinnerung",
    year: "2024",
    medium: "Oil on canvas",
    dimensions: "125 × 135 cm",
    description: "A contemplative work exploring the enchantment of memory. Layers of color and texture create a dialogue between past and present, inviting the viewer into a space of reflection. 125 × 135 cm",
    image: "/paintings/zauber-der-erinnerung-2024.jpg",
    thumbnail: "/paintings/zauber-der-erinnerung-2024.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "22",
    slug: "oriens-2018",
    title: "Oriens",
    year: "2018",
    medium: "Oil on canvas",
    dimensions: "68 × 60 cm",
    description: "Rising light—a meditation on emergence and dawn. The painting captures the quiet moment of awakening where colors begin to coalesce from darkness, exploring the threshold between night and illumination. 68 × 60 cm",
    image: "/paintings/oriens-2018.jpg",
    thumbnail: "/paintings/oriens-2018.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "23",
    slug: "molten-gold-2018",
    title: "Molten Gold",
    year: "2018",
    medium: "Oil on canvas",
    dimensions: "125 × 130 cm",
    description: "Molten Gold, 2018, oil on canvas. A dense field of shifting light and earth tones, where luminous warmth rises from within the surface. The painting hovers between landscape and abstraction, suggesting horizon, air, and deep ground without resolving into a fixed image. 125 × 130 cm",
    image: "/paintings/molten-gold-2018.jpg",
    thumbnail: "/paintings/molten-gold-2018.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "24",
    slug: "sub-mars-2018",
    title: "Sub Mars",
    year: "2018",
    medium: "Oil on canvas",
    dimensions: "75 × 95 cm",
    description: "Sub Mars, 2018, oil on canvas. A muted, mineral field where rusty reds and earthen greens seem to glow from beneath the surface, as if filtered through atmospheric distance. The painting suggests a terrain viewed from far above or far within, hovering between geological memory and quiet cosmic drift. 75 × 95 cm",
    image: "/paintings/sub-mars-2018.jpg",
    thumbnail: "/paintings/sub-mars-2018.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "25",
    slug: "wasteland-2017",
    title: "Wasteland",
    year: "2017",
    medium: "Oil on canvas",
    dimensions: "130 × 140 cm",
    description: "A meditation on barren or depleted terrain. Muted tones and spare forms suggest aftermath, resilience, or the slow reclamation of space.",
    image: "/paintings/wasteland-2017.jpg",
    thumbnail: "/paintings/wasteland-2017.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "26",
    slug: "la-mort-douce-2017",
    title: "La Mort Douce",
    year: "2017",
    medium: "Oil on canvas",
    dimensions: "85 × 90 cm",
    description: "A contemplative space where gentle tones and quiet transitions evoke acceptance, rest, or the threshold between presence and absence.",
    image: "/paintings/la-mort-douce-2017.jpg",
    thumbnail: "/paintings/la-mort-douce-2017.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "27",
    slug: "salt-of-the-earth-2017",
    title: "Salt Of The Earth",
    year: "2017",
    medium: "Oil on canvas",
    dimensions: "125 × 125 cm",
    description: "Earthy, grounded presence. The painting suggests substance and foundation—essential matter and light with a tactile sense of the elemental.",
    image: "/paintings/salt-of-the-earth-2017.jpg",
    thumbnail: "/paintings/salt-of-the-earth-2017.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "28",
    slug: "electric-flow-2017",
    title: "Electric Flow",
    year: "2017",
    medium: "Oil on canvas",
    dimensions: "115 × 125 cm",
    description: "Currents of energy and light. Dynamic movement and luminous passages suggest charge, flow, and the invisible forces that move through form.",
    image: "/paintings/electric-flow-2017.jpg",
    thumbnail: "/paintings/electric-flow-2017.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "29",
    slug: "temptation-2017",
    title: "Temptation",
    year: "2017",
    medium: "Oil on canvas",
    dimensions: "90 × 115 cm",
    description: "A tension between restraint and desire. The image holds suggestion and ambiguity, inviting the viewer into a space of sensory or moral threshold.",
    image: "/paintings/temptation-2017.jpg",
    thumbnail: "/paintings/temptation-2017.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "30",
    slug: "the-bitter-so-pale-and-sweet-2017",
    title: "The bitter, so pale and sweet",
    year: "2017",
    medium: "Oil on canvas",
    dimensions: "58 × 58 cm",
    description: "Contrast and paradox—bitter and sweet, pale and intense. The painting explores the meeting of opposites and the complexity of sensation.",
    image: "/paintings/the-bitter-so-pale-and-sweet-2017.jpg",
    thumbnail: "/paintings/the-bitter-so-pale-and-sweet-2017.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "31",
    slug: "scenery-2016",
    title: "Scenery",
    year: "2016",
    medium: "Oil on canvas",
    dimensions: "125 × 135 cm",
    description: "A meditation on place and view. The work hovers between representation and atmosphere, offering a sense of terrain without fixing it.",
    image: "/paintings/scenery-2016.jpg",
    thumbnail: "/paintings/scenery-2016.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "32",
    slug: "blur-2015",
    title: "Blur",
    year: "2015",
    medium: "Oil on canvas",
    dimensions: "80 × 90 cm",
    description: "Soft edges and dissolved boundaries. The painting explores the moment when form loses definition and merges into light, memory, or transition.",
    image: "/paintings/blur-2015.jpg",
    thumbnail: "/paintings/blur-2015.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "33",
    slug: "solanum-2015",
    title: "Solanum",
    year: "2015",
    medium: "Oil on canvas",
    dimensions: "115 × 100 cm",
    description: "Botanical or organic undertones. The work suggests growth, ambiguity, or the layered beauty of the nightshade—dark and fertile.",
    image: "/paintings/solanum-2015.jpg",
    thumbnail: "/paintings/solanum-2015.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "34",
    slug: "the-missing-link",
    title: "The Missing Link (The Two Of Us)",
    year: "2014",
    medium: "Oil on canvas",
    dimensions: "145 × 135 cm",
    description: "Connection and absence. The painting explores relationship, the space between two, or the search for what bridges separation.",
    image: "/paintings/the-missing-link.jpg",
    thumbnail: "/paintings/the-missing-link.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "35",
    slug: "letat-du-coeur-2014",
    title: "L' État du Coeur",
    year: "2014",
    medium: "Oil on canvas",
    dimensions: "65 × 95 cm",
    description: "The state of the heart—a contemplative space where feeling and form meet. The painting explores inner landscape and emotional resonance through color and gesture.",
    image: "/paintings/letat-du-coeur.jpg",
    thumbnail: "/paintings/letat-du-coeur.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "36",
    slug: "manacor-2013",
    title: "Manacor",
    year: "2013",
    medium: "Oil on canvas",
    dimensions: "115 × 135 cm",
    description: "A sense of place distilled into light and color. The work evokes terrain and atmosphere—perhaps Mediterranean—without fixing the view, leaving space for memory and association.",
    image: "/paintings/manacor.jpg",
    thumbnail: "/paintings/manacor.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "37",
    slug: "transition-2013",
    title: "Transition",
    year: "2013",
    medium: "Oil on canvas",
    dimensions: "120 × 140 cm",
    description: "The threshold between one state and another. The painting captures movement and change—color and form in flux, suggesting the moment when something becomes something else.",
    image: "/paintings/transition.jpg",
    thumbnail: "/paintings/transition.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "38",
    slug: "damp-dawn-2012",
    title: "Damp Dawn",
    year: "2012",
    medium: "Oil on canvas",
    dimensions: "110 × 105 cm",
    description: "First light and moisture. The painting evokes the quiet hour when night lifts—cool tones, soft edges, and a sense of the world not yet fully revealed.",
    image: "/paintings/damp-dawn.jpg",
    thumbnail: "/paintings/damp-dawn.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "39",
    slug: "point-of-peculiarity-2012",
    title: "Points Of Peculiarity",
    year: "2012",
    medium: "Oil on canvas",
    dimensions: "37 × 41 cm",
    description: "Small moments of strangeness or singularity. The work focuses on the particular—a detail, a deviation—where the familiar tilts toward the unexpected.",
    image: "/paintings/point-of-pecularity.jpg",
    thumbnail: "/paintings/point-of-pecularity.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "40",
    slug: "idle-impression-2012",
    title: "Idle Impression",
    year: "2012",
    medium: "Oil on canvas",
    dimensions: "45 × 60 cm",
    description: "A trace of something half-noticed. The painting holds the quality of reverie—forms and colors that linger without demanding resolution, like a thought that never quite lands.",
    image: "/paintings/idle-impression.jpg",
    thumbnail: "/paintings/idle-impression.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "41",
    slug: "before-the-aftermath-2010",
    title: "Before the Aftermath",
    year: "2010",
    medium: "Oil on canvas",
    dimensions: "105 × 105 cm",
    description: "The calm or tension that precedes consequence. The work hovers in a moment of suspension—before the story resolves—inviting reflection on what has not yet happened.",
    image: "/paintings/before-the-aftermath.jpg",
    thumbnail: "/paintings/before-the-aftermath.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "42",
    slug: "distant-healing-2009",
    title: "Distant Healing",
    year: "2009",
    medium: "Oil on canvas",
    dimensions: "120 × 120 cm",
    description: "Connection across distance. The painting suggests care, repair, or presence that reaches beyond the immediate—a quiet meditation on what bridges separation.",
    image: "/paintings/distant-healing.jpg",
    thumbnail: "/paintings/distant-healing.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "43",
    slug: "meadow-2008",
    title: "Meadow",
    year: "2008",
    medium: "Oil on hardboard",
    dimensions: "30 × 30 cm",
    description: "A small field of color and light. The work evokes open ground—grass, growth, the simplicity of a single place—compressed into an intimate scale.",
    image: "/paintings/meadow.jpg",
    thumbnail: "/paintings/meadow.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
  {
    id: "44",
    slug: "weltenraum-1998",
    title: "Weltenraum",
    year: "1998",
    medium: "Oil on canvas",
    dimensions: "130 × 115 cm",
    description: "World-space—the room of the world. The painting explores expanse and containment, the place where inner and outer meet, in a meditation on scale and presence.",
    image: "/paintings/weltenraum.jpg",
    thumbnail: "/paintings/weltenraum.jpg",
    imgWidth: 920,
    imgHeight: 1164,
  },
]

export function getArtworkBySlug(slug: string): Artwork | undefined {
  return artworks.find((artwork) => artwork.slug === slug)
}

export function getArtworkIndex(slug: string): number {
  return artworks.findIndex((artwork) => artwork.slug === slug)
}

export function getPreviousArtwork(currentSlug: string): Artwork | undefined {
  const currentIndex = getArtworkIndex(currentSlug)
  if (currentIndex <= 0) return undefined
  return artworks[currentIndex - 1]
}

export function getNextArtwork(currentSlug: string): Artwork | undefined {
  const currentIndex = getArtworkIndex(currentSlug)
  if (currentIndex >= artworks.length - 1) return undefined
  return artworks[currentIndex + 1]
}
